twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: 'Symfony App'
#    form_themes: ['tailwind_2_layout.html.twig']
when@test:
    twig:
        strict_variables: true
